version: '3.9'

services:
  image.analyzer:
    image: ${DOCKER_REGISTRY-}${DOCKER_NAMESPACE:-dock}/image-analyzer:${VERSION:-latest}
    build:
      context: .
      dockerfile: ImageAnalyzer.Api/Dockerfile
      target: ${DOCKER_BUILD_TARGET:-final}
      args: 
        version: ${DOCKER_REGISTRY-}${DOCKER_NAMESPACE:-dock}/image-analyzer:${SOURCE_VERSION}

