version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: image-image-analyzer-api
    container_name: container-image-analyzer-api
    ports:
      - "5000:80"
      - "443:443"
    environment:
      - AppConfiguration__Amazon__AwsAccessKey = ${AWS_ACCESS_KEY}
      - AppConfiguration__Amazon__AwsAccessSecret = ${AWS_ACCESS_SECRET}