# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Verify code format
      run: dotnet format --verify-no-changes
    - name: Restore dependencies
      run: dotnet restore 'ImageAnalyzer.Api/ImageAnalyzer.Api.csproj'
    - name: Build
      run: dotnet build 'ImageAnalyzer.Api/ImageAnalyzer.Api.csproj' --no-restore
    - name: Test
      run: dotnet test 'ImageAnalyzer.Api/ImageAnalyzer.Api.csproj' --no-build --verbosity normal
    - name: Publish
      run: dotnet publish 'ImageAnalyzer.Api/ImageAnalyzer.Api.csproj' --configuration Release -o '${{ github.workspace }}/out' -r linux-x64 --self-contained false
